server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecobridge_recycler
    username: postgres
    password: divyansh123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/