spring:
  application:
    name: recycler-service

  profiles:
    active: dev


  config:
    import: optional:configserver:https://ecobridge-enterprise.onrender.com

management:
  endpoints:
    web:
      exposure:
        include: "*"