server:
  port: 8088

spring:

  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/ecobridge_notification
    username: postgres
    password: divyansh123

  kafka:
    bootstrap-servers: ecobridge-kafka:9092

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/