server:
  port: 8088

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/ecobridge_notification
    username: postgres
    password: divyansh123

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    properties:
      spring.json.trusted.packages: "*"

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"