spring:
  cloud:
    gateway:
      routes:

        - id: auth-route
          uri: https://ecobridge-enterprise-2.onrender.com
          predicates:
            - Path=/api/v1/auth/**

        - id: oauth-route
          uri: https://ecobridge-enterprise-2.onrender.com
          predicates:
            - Path=/oauth2/**

        - id: oauth-login-route
          uri: https://ecobridge-enterprise-2.onrender.com
          predicates:
            - Path=/login/oauth2/**

        - id: user-route
          uri: https://ecobridge-enterprise-2.onrender.com
          predicates:
            - Path=/api/v1/users/**

        - id: waste-route
          uri: https://ecobridge-enterprise-3.onrender.com
          predicates:
            - Path=/api/v1/waste/**

        - id: upload-route
          uri: https://ecobridge-enterprise-3.onrender.com
          predicates:
            - Path=/api/v1/upload/**

        - id: recycler-route
          uri: https://ecobridge-enterprise-4.onrender.com
          predicates:
            - Path=/api/v1/recycler/**

        - id: matching-route
          uri: https://ecobridge-enterprise-6.onrender.com
          predicates:
            - Path=/api/v1/matching/**

        - id: analytics-route
          uri: https://ecobridge-enterprise-7.onrender.com
          predicates:
            - Path=/api/v1/analytics/**

        - id: notification-route
          uri: https://ecobridge-enterprise-5.onrender.com
          predicates:
            - Path=/api/v1/notifications/**