server:
  port: 8081
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
              - openid

          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - user:email
              - read:user

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

security:
  jwt:
    secret: ${JWT_SECRET:1234567890123456789012345678901234567890123456789012345678901234}
    issuer: ${JWT_ISSUER:api.project-auth.com}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}
    cookie-secure: ${JWT_COOKIE_SECURE:true}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:lax}
    cookie-domain: ${JWT_COOKIE_DOMAIN:}

app:
  cors:
    front-end-url: ${FRONT_END_URL:http://localhost}

  auth:
    frontend:
      success-redirect: ${FRONT_END_SUCCESS_REDIRECT:http://localhost/oauth/success}
      failure-redirect: ${FRONT_END_FAILURE_REDIRECT:http://localhost/oauth/failure}

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.security.oauth2.client.web: TRACE
    org.springframework.web.HttpSession: TRACE
    org.springframework.session: TRACE