apiVersion: v1
kind: Service

metadata:
  name: notification-service
  namespace: ecobridge

spec:
  selector:
    app: notification-service

  ports:
    - port: 8088
      targetPort: 8088

  type: ClusterIP