spring:
  application:
    name: auth-service



  config:
    import: configserver:https://ecobridge-enterprise.onrender.com

management:
  server:
    port: 8081

  endpoints:
    access:
      default: unrestricted

    web:
      exposure:
        include: "*"

  endpoint:
    health:
      access: unrestricted
      show-details: always

    info:
      access: unrestricted  