spring:
  application:
    name: auth-service

  config:
    import: optional:configserver:https://ecobridge-enterprise.onrender.com

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

management:
  server:
    port: 8081

  endpoints:
    access:
      default: unrestricted

    web:
      exposure:
        include: "*"

  endpoint:
    health:
      access: unrestricted
      show-details: always

    info:
      access: unrestricted