apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-service
  namespace: ecobridge

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      containers:
        - name: auth-service
          image: ecobridge/auth-service:1.0

          ports:
            - containerPort: 8081

          envFrom:
            - configMapRef:
                name: ecobridge-config

            - secretRef:
                name: ecobridge-secret

          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"

            - name: EUREKA_SERVER_URL
              value: "http://discovery-server:8761/eureka/"

            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/ecobridge_auth"

            - name: FRONT_END_URL
              value: "http://ecobridge.local"

            - name: FRONT_END_SUCCESS_REDIRECT
              value: "http://ecobridge.local/oauth/success"

            - name: FRONT_END_FAILURE_REDIRECT
              value: "http://ecobridge.local/oauth/failure"