apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: ecobridge

spec:
  replicas: 1

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend
          image: divyansh275/ecobridge-frontend:1.2
          imagePullPolicy: Always

          ports:
            - containerPort: 80