spring:
  application:
    name: waste-service

  config:
    import: optional:configserver:https://ecobridge-enterprise.onrender.com

security:
  jwt:
    secret: ${JWT_SECRET}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}