server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecobridge_matching
    username: postgres
    password: divyansh123


security:
  jwt:
    secret: ${JWT_SECRET}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/