server:
  port: 8761

spring:
  application:
    name: discovery-server

  config:
    import: ${CONFIG_SERVER_URL:optional:configserver:http://config-server:8888}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    wait-time-in-ms-when-sync-empty: 0