server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:https://ecobridge-enterprise.onrender.com

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

management:
  endpoints:
    web:
      exposure:
        include: "*"