apiVersion: apps/v1
kind: Deployment

metadata:
  name: discovery-server
  namespace: ecobridge

spec:
  replicas: 1

  selector:
    matchLabels:
      app: discovery-server

  template:
    metadata:
      labels:
        app: discovery-server

    spec:
      containers:
        - name: discovery-server
          image: ecobridge/discovery-server:1.0

          ports:
            - containerPort: 8761

          env:
            - name: SPRING_CONFIG_IMPORT
              value: "optional:configserver:http://config-server:8888"